### PR TITLE
Upgrade upload-artifact action from v3 to v4

### LINKED ISSUE #91: upload-artifact@v3 is deprecated
https://github.com/zaproxy/action-full-scan/blob/a9fbae9d7b2aae20ee32fe3b400d760e65c4e9a1/.github/workflows/check-dist.yml#L47

This was [deprecated on April 14, 2024](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) and will not be usable on November 30, 2024. I hope it's an easy upgrade and that the [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) don't impact this work.

### PR DESCRIPTION
**Pull request by jc00ke**
Closes #91

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by thc202** [comment]
Closing, we'll be using a reusable workflow.

**Comment by lgmorand** [comment]
@thc202 Hi when do you plan to fix it ? the PR at least fixes the issue until you write something else.

**Comment by thc202** [comment]
See https://github.com/zaproxy/action-full-scan/issues/91#issuecomment-2323203906

**Pull request closed without merging**
