### PR TITLE
Add warning that ZAP will submit forms

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Link to the FAQ?

**Comment by psiinon** [comment]
Sounds good - on "large number of messages from 'Contact us' forms", just "'Contact us' forms" or ??

**Comment by psiinon** [comment]
Have changed it.

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
